const game = {
    team1: 'Bayern Munich',
    team2: 'Borrussia Dortmund',
    allPlayers : [
        [
            'S1',
            'S2',
            'S3',
            'S4',
            'S5',
            'S6',
            'S7',
            'S8',
            'S9',
            'S10',
            'S11',
        ],
        [
            'S1.1',
            'S2.1',
            'S3.1',
            'S4.1',
            'S5.1',
            'S6.1',
            'S7.1',
            'S8.1',
            'S9.1',
            'S10.1',
            'S11.1',
        ],
    ],
    score: '4:0',
    scored: ['S1','S2','S5','S8'],
    date: 'Nov 9th, 2099',
    odds: {
        team1: 1.33,
        x: 3.25,
        team2: 6.5,
    },
};